spring:
  application:
    name: catboardback
  datasource:
    url: jdbc:mysql://localhost:3306/catdb
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

boardImgLocation: C:/Users/codehows/Documents/GitHub/CatBoardBack/board
uploaPath: file:///C:/CatBoardBack/
